version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  client:
    build:
      context: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client/school-platform:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
